### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'models/lin_svc.sav'

### ISSUE THREAD

**Issue by simplesaad** [Aftaab99/Heart-Disease-Diagnosis#2]
I'm getting this error after submitting the values in the flask webpage.
![image](https://user-images.githubusercontent.com/29461284/54833776-c43b8400-4ce4-11e9-9a80-8c262d66e78e.png)

**Comment by Aftaab99** [comment]
I had used a linear svm earlier, then switched to a RandomForestClassifier. I had forgotten to change the path. Thanks for the opening the issue.

**Comment by vishalvr25** [comment]
can you please use all the 14 attributes to find the heart disease
